version: '3.8'

services:

server:
  build: .
  restart: always
   ports:
      - "8080:8080"
   depends_on:
    - mysqldb
    networks:
      - mysql

  mysqldb:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:admin
      MYSQL_PASSWORD:root
      MYSQL_DATABASE: test1
    restart: always
    ports:
      - "3308:3306"
      networks:
      - mysql
      
      networks:
      mysql:
