version: '3.8'

services:

server:
  build: .
  restart: always
   ports:
      - "8080:8080"
   depends_on:
    - mysqldb
    networks:
      - mysql
      environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/test1?useSSL=false

  mysqldb:
  container_name: mysqldb
    image: mysql:8.0.17
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:root
      MYSQL_PASSWORD:root
      MYSQL_DATABASE: test1
      MYSQL_ROOT_HOST: '%'
    restart: always
    ports:
      - "3308:3306"
      networks:
      - mysql
      
      networks:
      mysql:
